host:
  model_name: "your_model_name"
  base_url: "your_url"
  api_key: "your key"
specialist:
  user_service:
    model_name: "your_model_name"
    base_url: "your_url"
    api_key:  "your_key"
tool:
  mcp:
    user_service:
      base_url: "your_url"
      api_key: "your_key"